/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/consult': typeof ConsultRoute
  '/doctor': typeof DoctorRoute
  '/portal': typeof PortalRoute
  '/treatments': typeof TreatmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/consult': typeof ConsultRoute
  '/doctor': typeof DoctorRoute
  '/portal': typeof PortalRoute
  '/treatments': typeof TreatmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking': typeof BookingRoute
  '/consult': typeof ConsultRoute
  '/doctor': typeof DoctorRoute
  '/portal': typeof PortalRoute
  '/treatments': typeof TreatmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking'
    | '/consult'
    | '/doctor'
    | '/portal'
    | '/treatments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/booking'
    | '/consult'
    | '/doctor'
    | '/portal'
    | '/treatments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking'
    | '/consult'
    | '/doctor'
    | '/portal'
    | '/treatments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingRoute: typeof BookingRoute
  ConsultRoute: typeof ConsultRoute
  DoctorRoute: typeof DoctorRoute
  PortalRoute: typeof PortalRoute
  TreatmentsRoute: typeof TreatmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingRoute: BookingRoute,
  ConsultRoute: ConsultRoute,
  DoctorRoute: DoctorRoute,
  PortalRoute: PortalRoute,
  TreatmentsRoute: TreatmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
